app:
  version: ${project.version}
  name: ${project.name}

server:
  error:
    path: '/error'
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  profiles:
    active: dev
  test:
    constructor:
      autowire:
        mode: all
  main:
    allow-circular-references: true
  output:
    ansi:
      enabled: detect
  messages:
    basename: i18n/exception
    encoding: UTF-8
  datasource:
    url: jdbc:h2:file:./dbdata/place
    driver-class-name: org.h2.Driver
    username: place
    password: place
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
      jdbc:
        batch_size: 100
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS}|%clr(%-5level)|%clr(%F){cyan}:%L|%clr(%logger{0}){blue}|%clr(%M){magenta}|%msg%n"
  level:
    root: info
    org.example.advice.*: debug
    org.example.service.*: info

---
# openapi option 참고: https://springdoc.org/#properties
springdoc:
  api-docs:
    groups:
      enabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    path: /swagger-ui
    disable-swagger-default-url: false
    display-query-params-without-oauth2: true
  paths-to-match:
    - /**
  packages-to-exclude:
    - org.example.common

scheduler:
  statistics:
    cron: "*/10 * * * * *"

#schedlock:
#  table: schedlock

kakao:
  api:
    host: https://dapi.kakao.com
    app-key: KakaoAK 87b8f9ebad706807ff485be92f3f147c
    format: json
    timeout: 10000

naver:
  api:
    host: https://openapi.naver.com
    client-id: O7dzJxdO1uWlqDjUw4On
    client-secret: 3nV4Pe6oFS
    format: json
    timeout: 10000